ART-11111: versioning scheme decides the right param value for Jira t…
openshift-eng/art-tools pull request #1083
Opened 2024-10-22 14:29 UTC by mbiarnes

…emplate

rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

2024-11-01 08:39 UTC, joepvd requested changes
A comment, but maybe we should return to the drawing board.

2024-11-01 08:39 UTC, joepvd commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        # Convert string to an integer if necessary (like 4.20.0-0 will result in
Not sure why the line above does `to_tuple()`. the semver.version.Version instance has nice attributes:

```
>>> v = semver.VersionInfo.parse('4.5.6-1')
>>> v.to_dict()
{'major': 4, 'minor': 5, 'patch': 6, 'prerelease': '1', 'build': None}
>>> v.major
4
```

But this makes me realize that the proposed versioning scheme is not semver compliant. 

Most standard compliant solution would be to have this in the build info. 

```
>>> semver.VersionInfo.parse('4.5.6-1')
Version(major=4, minor=5, patch=6, prerelease='1', build=None)
>>> semver.VersionInfo.parse('4.5.6-rc.0-0')
Version(major=4, minor=5, patch=6, prerelease='rc.0-0', build=None)
```

meaning, for an RC, semver does not understand semantically understand what is going on. 

The scheme to denote our build after a `+` seems the standard way of doing it:
```
>>> semver.VersionInfo.parse('4.5.6-rc.0+0')
Version(major=4, minor=5, patch=6, prerelease='rc.0', build='0')
>>> semver.VersionInfo.parse('4.5.6-rc.0+1')
Version(major=4, minor=5, patch=6, prerelease='rc.0', build='1')
>>> semver.VersionInfo.parse('4.5.7+1')
Version(major=4, minor=5, patch=7, prerelease=None, build='1')
```

2024-11-01 08:39 UTC, joepvd commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +            "x": x,
would rather use the attributes semver returns, 

```python
self.release_version = semver.VersionInfo.parse(self.release_name)

# so here it becomes
"x": self.release_version.major
```

2024-11-01 13:33 UTC, joepvd commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        # Convert string to an integer if necessary (like 4.20.0-0 will result in
The doubt about the versioning scheme is resolved, `+` is not a valid token for a k8s object. We need to deviate from semver.

2026-04-14 10:25 UTC, mbiarnes commented
the new-version - system was never implemented

2026-04-14 10:25 UTC, closed without merging