ART-9021 Use official release schedule API
openshift-eng/art-tools pull request #437
Opened 2024-02-29 05:11 UTC by Ximinhan

Our tool is using Release_schedule lib to get release schedule through gitlab release schedule [repo](https://gitlab.cee.redhat.com/ocp-release-schedule/schedule/-/blob/master/schedules/4.15.yaml?ref_type=heads), while the repo is updated by us ref the official release schedule on pp.engineering.redhat.com.

This pr replace the function to directly get feature freeze release date from release schedule API, also add function to get GA date through API.

2024-02-29 10:20 UTC, joepvd commented
/hold

While I think the current situation is not good, I do not trust pp enough yet to have it change base images and golang builders without us being aware. 

Thinking of this approach:
- we get rid of `auto` in `canonical_builders_from_upstream`
- we get a notification if pp says branch cut happened, and we have it still on `true`

2024-02-29 10:30 UTC, locriandev requested changes

2024-02-29 10:30 UTC, locriandev commented on artcommon/artcommonlib/util.py
> +    release_schedules = requests.get(f'{RELEASE_SCHEDULES}/openshift-{major}.{minor}/schedule-tasks/?name=OpenShift%20Container%20Platform%20GA%20Release%20Schedule', headers={'Accept': 'application/
```suggestion
    release_schedules = requests.get(
        f'{RELEASE_SCHEDULES}/openshift-{major}.{minor}/schedule-tasks/?name=OpenShift%20Container%20Platform%20GA%20Release%20Schedule',
        headers={'Accept': 'application/json'}
    )
```

2024-02-29 10:30 UTC, locriandev commented on doozer/doozerlib/distgit.py
>              except ChildProcessError:
This exception no longer needs to be caught

2024-02-29 11:08 UTC, Ximinhan commented on artcommon/artcommonlib/util.py
> +    release_schedules = requests.get(f'{RELEASE_SCHEDULES}/openshift-{major}.{minor}/schedule-tasks/?name=Feature%20Development%20for%20{major}.{minor}', headers={'Accept': 'application/json'})
the server is valid enough, I think the check response code is should be catch the invalid response, and when its empty the return valid is None and distgit check will raise the error when compare None and datetime.now()

2024-02-29 11:10 UTC, Ximinhan commented on artcommon/artcommonlib/util.py
> +def get_feature_freeze_release_date(major, minor):
ok to move

2024-02-29 11:15 UTC, Ximinhan commented
> /hold
> 
> While I think the current situation is not good, I do not trust pp enough yet to have it change base images and golang builders without us being aware.
> 
> Thinking of this approach:
> 
> * we get rid of `auto` in `canonical_builders_from_upstream`
> * we get a notification if pp says branch cut happened, and we have it still on `true`

I don't get what your approach means.
Do you need some reassurance about the pp.engineering.redhat.com? Instead, I think the release schedule repo may lack of update when  pp.engineering.redhat.com has a new change.

2024-02-29 11:31 UTC, Ximinhan commented on artcommon/artcommonlib/util.py
> +def get_feature_freeze_release_date(major, minor):
actually when I tried to move to release_util find there is a chain reference, get_inflight use get_assembly_release_date and get_ocp_version_from_group and is_future_release_date, I don't see a big difference to split into two util libs, instead we the two utils may have cross reference. So I would keep it in util.py

2024-03-05 14:29 UTC, Ximinhan commented on artcommon/artcommonlib/util.py
> +    release_schedules = requests.get(f'{RELEASE_SCHEDULES}/openshift-{major}.{minor}/schedule-tasks/?name=Feature%20Development%20for%20{major}.{minor}', headers={'Accept': 'application/json'})
retry added

2024-06-04 01:50 UTC, closed without merging